language: php

php:
  - 5.3
  - 5.6
  - 7.0
  
before_script:
  # Install Composer 
  - php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
  - php composer-setup.php
  - php -r "unlink('composer-setup.php');"
  # Install Composer dependencies
  - travis_retry php composer.phar self-update
  - travis_retry php composer.phar install
  
script:
  # Run unit tests
  - ./vendor/bin/phpunit --configuration tests/phpunit.xml --coverage-text --coverage-clover=coverage.clover

notifications:
  email:
    recipients:      
      - oleg@webmarketingroi.com.au
    on_success: always
    on_failure: always
