language: php

php:
  - 5.3
  - 5.6
  - 7.0
  
before_script:
  # Install Composer dependencies
  - travis_retry php composer.phar self-update
  - travis_retry php composer.phar install
  
script:
  # Run unit tests
  - ./vendor/bin/phpunit --configuration tests/phpunit.xml --coverage-text --coverage-clover=coverage.clover

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  
notifications:
  email:
    recipients:      
      - oleg@webmarketingroi.com.au
	on_success: always
    on_failure: always
